version: '3'

services:
    apache-php:
        build: .
        container_name: serverside_opgave
        volumes:
            - ./public:/var/www/html
        ports:
            - '8080:80'
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: collection
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - '3306:3306'

    phpmyadmin:
        container_name: phpmyadmin
        image: arm64v8/phpmyadmin:latest
        platform: linux/arm64/v8
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '8081:80'

volumes:
    db_data:
